repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: mixed-line-ending

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
    -   id: pylint
        additional_dependencies:
        - pylint-django
        - pylint-celery
        - pylint-flask
        - pylint-pytest

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-requests
        - types-PyYAML
        - types-python-dateutil
        - types-six

-   repo: https://github.com/PyCQA/doc8
    rev: 1.1.1
    hooks:
    -   id: doc8
        args: ["--max-line-length", "100"]

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    -   id: markdownlint
        args: ["--config", ".markdownlint.json"]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        args: ["--ignore-words-list=nd,ba,fo,datas,datasource,datasources,datastore,datastores,datastream,datastreams,datatype,datatypes,datasource,datasources,datastore,datastores,datastream,datastreams,datatype,datatypes"]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-log-warn
    -   id: python-use-type-annotations

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, html, md, yaml, yml]

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
    -   id: shellcheck
        args: ["--severity=warning"]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    -   id: eslint
        additional_dependencies:
        - eslint@8.56.0
        - eslint-config-prettier@9.1.0
        - eslint-plugin-prettier@5.1.3
        - eslint-plugin-react@7.33.2
        - eslint-plugin-react-hooks@4.6.0 