# ARPGuard API Configuration

# Authentication settings
authentication:
  method: jwt
  jwt_secret: ${JWT_SECRET}
  token_expiry: 24h

# Rate limiting settings
rate_limiting:
  enabled: true
  requests_per_minute: 60
  burst_size: 10

# API endpoints configuration
endpoints:
  - path: /api/v1/auth
    secure: false
    methods: [POST]
    description: Authentication endpoint
    
  - path: /api/v1/dashboard
    secure: true
    methods: [GET]
    description: Dashboard data endpoint
    
  - path: /api/v1/alerts
    secure: true
    methods: [GET, POST]
    description: Alerts management endpoint
    
  - path: /api/v1/config
    secure: true
    methods: [GET, PUT]
    description: Configuration management endpoint
    
  - path: /api/v1/reports
    secure: true
    methods: [GET, POST]
    description: Reports generation endpoint

# CORS settings
cors:
  enabled: true
  allowed_origins: ['*']
  allowed_methods: ['GET', 'POST', 'PUT', 'DELETE']
  allowed_headers: ['Content-Type', 'Authorization']

# Logging settings
logging:
  enabled: true
  level: info
  file: logs/api.log 